services:
  # --- REDIS MASTER (Para escrituras del líder) ---
  redis-master:
    image: redis:7-alpine
    container_name: redis_master
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  # --- REDIS REPLICA (Para lecturas de cualquier nodo) ---
  redis-replica:
    image: redis:7-alpine
    container_name: redis_replica
    ports:
      - "6380:6379"
    command: redis-server --replicaof redis-master 6379 --appendonly yes
    depends_on:
      - redis-master

# --- REVERSE PROXY INTELIGENTE (Punto único de entrada gRPC) ---
  grpc-proxy:
    build:
      context: .
      dockerfile: apps/grpc-tracker-proxy/Dockerfile
    container_name: grpc_internal_proxy
    ports:
      - "5050:5050" # Tus microservicios externos le pegan a este puerto
    depends_on:
      - app-node-1
      - app-node-2
      - app-node-3


# --- INSTANCIAS DE LA APLICACIÓN EN RUST ---

  app-node-1:
    build:
      context: .
      dockerfile: apps/tracking-node/Dockerfile
    container_name: rust_app_node_1
    ports:
      - "3001:3000"
      - "50052:50051" # Puerto para comunicación entre nodos
    environment:
      - PEER_ID=1
      - DATABASE_LEADER_URL=redis://redis-master:6379
      - DATABASE_FOLLOWER_URL=redis://redis-replica:6379
      - CLUSTER_NODES=1=http://app-node-1:50051,2=http://app-node-2:50051,3=http://app-node-3:50051
    depends_on:
      - redis-master
      - redis-replica

  app-node-2:
    build:
      context: .
      dockerfile: apps/tracking-node/Dockerfile
    container_name: rust_app_node_2
    ports:
      - "3002:3000"
      - "50053:50051" # Puerto para comunicación entre nodos
    environment:
      - PEER_ID=2
      - DATABASE_LEADER_URL=redis://redis-master:6379
      - DATABASE_FOLLOWER_URL=redis://redis-replica:6379
      - CLUSTER_NODES=1=http://app-node-1:50051,2=http://app-node-2:50051,3=http://app-node-3:50051
    depends_on:
      - redis-master
      - redis-replica

  app-node-3:
    build:
      context: .
      dockerfile: apps/tracking-node/Dockerfile
    container_name: rust_app_node_3
    ports:
      - "3003:3000"
      - "50054:50051" # Puerto para comunicación entre nodos
    environment:
      - PEER_ID=3
      - DATABASE_LEADER_URL=redis://redis-master:6379
      - DATABASE_FOLLOWER_URL=redis://redis-replica:6379
      - CLUSTER_NODES=1=http://app-node-1:50051,2=http://app-node-2:50051,3=http://app-node-3:50051
    depends_on:
      - redis-master
      - redis-replica

volumes:
  primario_data:
  replica_data: