services:
  # --- REDIS ---
  redis-master:
    image: redis:7-alpine
    container_name: redis_master
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  redis-replica:
    image: redis:7-alpine
    container_name: redis_replica
    ports:
      - "6380:6379"
    command: redis-server --replicaof redis-master 6379 --appendonly yes
    depends_on:
      - redis-master

  # --- API GATEWAY ---
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.go.dev
    container_name: go_api_gateway
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GRPC_PROXY_URL=grpc_internal_proxy:5050
      - RESTAURANT_APP_URL=restaurant_app:3000
    volumes:
      - /home/alan/rust-project/axum-peya:/app
      - /app/apps/api-gateway/tmp
    depends_on:
      - grpc-proxy
      - restaurant-app


  # --- RESTAURANT APP ---
  restaurant-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: restaurant_app
    ports:
      - "3030:3000"
    environment:
      - TRACKER_SERVICE_URL=http://grpc_internal_proxy:5050
      - CARGO_TARGET_DIR=/app/.target_docker/restaurant-app
    depends_on:
      - grpc-proxy
    volumes:
      - /home/alan/rust-project/axum-peya:/app
    
    command: ["cargo-watch", "-i", "target/*", "-i", ".target_docker/*", "-x", "run --package restaurant"]

  # --- REVERSE PROXY ---
  grpc-proxy:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: grpc_internal_proxy
    ports:
      - "5050:5050"
    volumes:
      - /home/alan/rust-project/axum-peya:/app
    environment:
      - CARGO_TARGET_DIR=/app/.target_docker/proxy
    command: ["cargo", "watch", "-i", "target/*", "-i", ".target_docker/*", "-x", "run --package grpc-tracker-proxy"]
    depends_on:
      - app-node-1
      - app-node-2
      - app-node-3

  # --- EL COMPILADOR PRINCIPAL (NODO 1) ---
  app-node-1:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rust_app_node_1
    ports:
      - "3001:3000"
      - "50052:50051"
    environment:
      - PEER_ID=1
      - DATABASE_LEADER_URL=redis://redis-master:6379
      - DATABASE_FOLLOWER_URL=redis://redis-replica:6379
      - CLUSTER_NODES=1=http://app-node-1:50051,2=http://app-node-2:50051,3=http://app-node-3:50051
      - CARGO_TARGET_DIR=/app/.target_docker/shared-nodes
    volumes:
      - /home/alan/rust-project/axum-peya:/app
    command: ["cargo-watch", "-i", "target/*", "-i", ".target_docker/*", "-x", "run --package tracker-node"]
    depends_on:
      - redis-master
      - redis-replica

  # --- REPLICA 2
  app-node-2:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rust_app_node_2
    ports:
      - "3002:3000"
      - "50053:50051"
    environment:
      - PEER_ID=2
      - DATABASE_LEADER_URL=redis://redis-master:6379
      - DATABASE_FOLLOWER_URL=redis://redis-replica:6379
      - CLUSTER_NODES=1=http://app-node-1:50051,2=http://app-node-2:50051,3=http://app-node-3:50051
    volumes:
      - /home/alan/rust-project/axum-peya:/app
    
    command: ["nodemon", "--watch", "/app/.target_docker/shared-nodes/debug/tracker-node", "--exec", "/app/.target_docker/shared-nodes/debug/tracker-node"]
    depends_on:
      - app-node-1

  # --- REPLICA 3 
  app-node-3:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rust_app_node_3
    ports:
      - "3003:3000"
      - "50054:50051"
    environment:
      - PEER_ID=3
      - DATABASE_LEADER_URL=redis://redis-master:6379
      - DATABASE_FOLLOWER_URL=redis://redis-replica:6379
      - CLUSTER_NODES=1=http://app-node-1:50051,2=http://app-node-2:50051,3=http://app-node-3:50051
    volumes:
      - /home/alan/rust-project/axum-peya:/app
    command: ["nodemon", "--watch", "/app/.target_docker/shared-nodes/debug/tracker-node", "--exec", "/app/.target_docker/shared-nodes/debug/tracker-node"]
    depends_on:
      - app-node-1
volumes:
  primario_data:
  replica_data: