FROM rust:latest

# Instalamos protobuf, nodejs y nodemon (un watcher de procesos ultra liviano)
RUN apt-get update && apt-get install -y protobuf-compiler nodejs npm && rm -rf /var/lib/apt/lists/*
RUN npm install -g nodemon
RUN cargo install cargo-watch

WORKDIR /app

EXPOSE 3000
EXPOSE 50051

CMD ["cargo", "watch", "-x", "check"]