// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/tracker/tracker-service.proto

package tracker_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestaurantLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantLocationRequest) Reset() {
	*x = RestaurantLocationRequest{}
	mi := &file_proto_tracker_tracker_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantLocationRequest) ProtoMessage() {}

func (x *RestaurantLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tracker_tracker_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantLocationRequest.ProtoReflect.Descriptor instead.
func (*RestaurantLocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_tracker_tracker_service_proto_rawDescGZIP(), []int{0}
}

func (x *RestaurantLocationRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RestaurantLocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *RestaurantLocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *RestaurantLocationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NearbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	RadiusKm      float64                `protobuf:"fixed64,3,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyRequest) Reset() {
	*x = NearbyRequest{}
	mi := &file_proto_tracker_tracker_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyRequest) ProtoMessage() {}

func (x *NearbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tracker_tracker_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyRequest.ProtoReflect.Descriptor instead.
func (*NearbyRequest) Descriptor() ([]byte, []int) {
	return file_proto_tracker_tracker_service_proto_rawDescGZIP(), []int{1}
}

func (x *NearbyRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *NearbyRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *NearbyRequest) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

type NearbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantIds []string               `protobuf:"bytes,1,rep,name=restaurant_ids,json=restaurantIds,proto3" json:"restaurant_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyResponse) Reset() {
	*x = NearbyResponse{}
	mi := &file_proto_tracker_tracker_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyResponse) ProtoMessage() {}

func (x *NearbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tracker_tracker_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyResponse.ProtoReflect.Descriptor instead.
func (*NearbyResponse) Descriptor() ([]byte, []int) {
	return file_proto_tracker_tracker_service_proto_rawDescGZIP(), []int{2}
}

func (x *NearbyResponse) GetRestaurantIds() []string {
	if x != nil {
		return x.RestaurantIds
	}
	return nil
}

type GenericResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	mi := &file_proto_tracker_tracker_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tracker_tracker_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_proto_tracker_tracker_service_proto_rawDescGZIP(), []int{3}
}

func (x *GenericResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenericResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_tracker_tracker_service_proto protoreflect.FileDescriptor

const file_proto_tracker_tracker_service_proto_rawDesc = "" +
	"\n" +
	"#proto/tracker/tracker-service.proto\x12\atracker\"y\n" +
	"\x19RestaurantLocationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"f\n" +
	"\rNearbyRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\tradius_km\x18\x03 \x01(\x01R\bradiusKm\"7\n" +
	"\x0eNearbyResponse\x12%\n" +
	"\x0erestaurant_ids\x18\x01 \x03(\tR\rrestaurantIds\"E\n" +
	"\x0fGenericResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb1\x01\n" +
	"\x0fTrackingService\x12U\n" +
	"\x15AddRestaurantLocation\x12\".tracker.RestaurantLocationRequest\x1a\x18.tracker.GenericResponse\x12G\n" +
	"\x14GetNearbyRestaurants\x12\x16.tracker.NearbyRequest\x1a\x17.tracker.NearbyResponseB5Z3axum-peya/api-gateway/proto/tracker/tracker-serviceb\x06proto3"

var (
	file_proto_tracker_tracker_service_proto_rawDescOnce sync.Once
	file_proto_tracker_tracker_service_proto_rawDescData []byte
)

func file_proto_tracker_tracker_service_proto_rawDescGZIP() []byte {
	file_proto_tracker_tracker_service_proto_rawDescOnce.Do(func() {
		file_proto_tracker_tracker_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tracker_tracker_service_proto_rawDesc), len(file_proto_tracker_tracker_service_proto_rawDesc)))
	})
	return file_proto_tracker_tracker_service_proto_rawDescData
}

var file_proto_tracker_tracker_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_tracker_tracker_service_proto_goTypes = []any{
	(*RestaurantLocationRequest)(nil), // 0: tracker.RestaurantLocationRequest
	(*NearbyRequest)(nil),             // 1: tracker.NearbyRequest
	(*NearbyResponse)(nil),            // 2: tracker.NearbyResponse
	(*GenericResponse)(nil),           // 3: tracker.GenericResponse
}
var file_proto_tracker_tracker_service_proto_depIdxs = []int32{
	0, // 0: tracker.TrackingService.AddRestaurantLocation:input_type -> tracker.RestaurantLocationRequest
	1, // 1: tracker.TrackingService.GetNearbyRestaurants:input_type -> tracker.NearbyRequest
	3, // 2: tracker.TrackingService.AddRestaurantLocation:output_type -> tracker.GenericResponse
	2, // 3: tracker.TrackingService.GetNearbyRestaurants:output_type -> tracker.NearbyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tracker_tracker_service_proto_init() }
func file_proto_tracker_tracker_service_proto_init() {
	if File_proto_tracker_tracker_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tracker_tracker_service_proto_rawDesc), len(file_proto_tracker_tracker_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tracker_tracker_service_proto_goTypes,
		DependencyIndexes: file_proto_tracker_tracker_service_proto_depIdxs,
		MessageInfos:      file_proto_tracker_tracker_service_proto_msgTypes,
	}.Build()
	File_proto_tracker_tracker_service_proto = out.File
	file_proto_tracker_tracker_service_proto_goTypes = nil
	file_proto_tracker_tracker_service_proto_depIdxs = nil
}
