syntax = "proto3";

package tracker;

service TrackingService {
  
  rpc AddRestaurantLocation (RestaurantLocationRequest) returns (GenericResponse);
  rpc GetNearbyRestaurants (NearbyRequest) returns (NearbyResponse);
}

message RestaurantLocationRequest {
  uint32 id = 1;
  double latitude = 2;
  double longitude = 3;
  string name = 4;
}

message NearbyRequest {
  double latitude = 1;
  double longitude = 2;
  double radius_km = 3;
}

message NearbyResponse {
  repeated string restaurant_ids = 1;
}

message GenericResponse {
  bool success = 1;
  string message = 2;
}