// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/restaurant/restaurant-service.proto

package restaurant_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestaurantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantRequest) Reset() {
	*x = RestaurantRequest{}
	mi := &file_proto_restaurant_restaurant_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantRequest) ProtoMessage() {}

func (x *RestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_restaurant_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantRequest.ProtoReflect.Descriptor instead.
func (*RestaurantRequest) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_restaurant_service_proto_rawDescGZIP(), []int{0}
}

func (x *RestaurantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestaurantRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RestaurantRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *RestaurantRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type GenericResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	mi := &file_proto_restaurant_restaurant_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_restaurant_restaurant_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_proto_restaurant_restaurant_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenericResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenericResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_restaurant_restaurant_service_proto protoreflect.FileDescriptor

const file_proto_restaurant_restaurant_service_proto_rawDesc = "" +
	"\n" +
	")proto/restaurant/restaurant-service.proto\x12\n" +
	"restaurant\"}\n" +
	"\x11RestaurantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\"E\n" +
	"\x0fGenericResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2`\n" +
	"\x11RestaurantService\x12K\n" +
	"\rNewRestaurant\x12\x1d.restaurant.RestaurantRequest\x1a\x1b.restaurant.GenericResponseB;Z9axum-peya/api-gateway/proto/restaurant/restaurant-serviceb\x06proto3"

var (
	file_proto_restaurant_restaurant_service_proto_rawDescOnce sync.Once
	file_proto_restaurant_restaurant_service_proto_rawDescData []byte
)

func file_proto_restaurant_restaurant_service_proto_rawDescGZIP() []byte {
	file_proto_restaurant_restaurant_service_proto_rawDescOnce.Do(func() {
		file_proto_restaurant_restaurant_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_restaurant_restaurant_service_proto_rawDesc), len(file_proto_restaurant_restaurant_service_proto_rawDesc)))
	})
	return file_proto_restaurant_restaurant_service_proto_rawDescData
}

var file_proto_restaurant_restaurant_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_restaurant_restaurant_service_proto_goTypes = []any{
	(*RestaurantRequest)(nil), // 0: restaurant.RestaurantRequest
	(*GenericResponse)(nil),   // 1: restaurant.GenericResponse
}
var file_proto_restaurant_restaurant_service_proto_depIdxs = []int32{
	0, // 0: restaurant.RestaurantService.NewRestaurant:input_type -> restaurant.RestaurantRequest
	1, // 1: restaurant.RestaurantService.NewRestaurant:output_type -> restaurant.GenericResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_restaurant_restaurant_service_proto_init() }
func file_proto_restaurant_restaurant_service_proto_init() {
	if File_proto_restaurant_restaurant_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_restaurant_restaurant_service_proto_rawDesc), len(file_proto_restaurant_restaurant_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_restaurant_restaurant_service_proto_goTypes,
		DependencyIndexes: file_proto_restaurant_restaurant_service_proto_depIdxs,
		MessageInfos:      file_proto_restaurant_restaurant_service_proto_msgTypes,
	}.Build()
	File_proto_restaurant_restaurant_service_proto = out.File
	file_proto_restaurant_restaurant_service_proto_goTypes = nil
	file_proto_restaurant_restaurant_service_proto_depIdxs = nil
}
